[workspace]
resolver = "2"
members = [
    "crates/bc_core",
    "crates/bc_cli",
    "crates/bc_qemu_riscv32",
    "crates/bc_c_api",
]
default-members = [
    "crates/bc_core",
    "crates/bc_cli",
    "crates/bc_c_api",
]
exclude = [
    "examples/m5stamp_c3",
]

[workspace.package]
version = "0.2.0"
edition = "2024"
license = "MIT"
