# Memory & Heap Configuration for M5Stamp C3 (ESP32-C3 400KB SRAM)
CONFIG_HEAP_MEM_POOL_SIZE=32768
CONFIG_COMMON_LIBC_MALLOC_ARENA_SIZE=32768

# USB-Serial JTAG Console Driver for M5Stamp C3 Type-C USB (/dev/ttyACM0)
CONFIG_SERIAL_ESP32_USB=y
